version: "3.9"




services:
  db:
    image: mysql/mysql-server
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ttMobileApp
      MYSQL_USER: root
      MYSQL_PASSWORD: toor

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    
volumes:
  db_data: {}
  rabbit_data: {}